os: linux
dist: trusty
sudo: required

language: node_js
node_js: "6"
cache: yarn
jdk: oraclejdk8
branches:
  only: fix_e2e

env:
  matrix:
    - MODE=prod
    - MODE=lint
    - MODE=unit
    - MODE=e2e

matrix:
  include:
    - env: MODE=docker
      sudo: required
      services: docker
      install: true
      cache: docker
  exclude:
    - env: MODE=docker
      sudo: false
      cache: yarn

before_install: chmod +x scripts/*.sh
before_script: scripts/build.sh
script: scripts/test.sh
after_success: scripts/deploy.sh

notifications:
  email:
    on_success: change
    on_failure: change
